### ISSUE TITLE
Issue with generating probe points with scaled surface

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaMPy#123]
Hi @hkjeldsberg, 

With `-sc 0.001` flag, VaMPy seems to fail generating probes. There is only one probe point at the inlet. 

![Screenshot 2023-09-26 at 15 02 44](https://github.com/KVSlab/VaMPy/assets/42674006/57a1f46c-558a-414c-9e31-d4c45a3ca6fa)

@johannesring  is investigating the issue right now.

**Comment by keiyamamo** [comment]
With `-rs 0.0001`, it worked fine! @hkjeldsberg  Should we also scale `resampling_step` when the `scale_factor` is given?

![Screenshot 2023-09-27 at 12 19 51](https://github.com/KVSlab/VaMPy/assets/42674006/f2c6a007-093a-4d4b-80fe-d92d336f6910)

**Comment by hkjeldsberg** [comment]
> With `-rs 0.0001`, it worked fine! @hkjeldsberg Should we also scale `resampling_step` when the `scale_factor` is given?
> 
> ![Screenshot 2023-09-27 at 12 19 51](https://user-images.githubusercontent.com/42674006/270946350-f2c6a007-093a-4d4b-80fe-d92d336f6910.png)

Happy to hear, @keiyamamo! Yes, it is probably a good idea to scale `resampling_step` based on the geometry scaling 👍
