### ISSUE TITLE
Wrong description of `T`?

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaMPy#135]
https://github.com/KVSlab/VaMPy/blob/2d1c05d45c83831da3664d708ce8d6b8697b3524/src/vampy/automatedPostprocessing/compute_flow_and_simulation_metrics.py#L22

`T` is defined as total simulation time, but I’m guessing it is actually the length of single cardiac cycle ?

**Comment by hkjeldsberg** [comment]
Good point! Updated this in #138
