### ISSUE TITLE
add comments on WSS computation

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaMPy#136]
https://github.com/KVSlab/VaMPy/blob/2d1c05d45c83831da3664d708ce8d6b8697b3524/src/vampy/automatedPostprocessing/postprocessing_common.py#L144

Point to make 
- works for P1P1, but not P2P1
- `p` is unused since pressure term disappears in the process of extracting tangential component.

**Comment by hkjeldsberg** [comment]
@keiyamamo Good point! I have added these points to the class description in #138
