### ISSUE TITLE
InternalError message

### ISSUE THREAD

**Issue by Owais-Khan** [KVSlab/VaMPy#46]
Hi, 

I just download vmtk, FEniCS and Vampy and trying it out. However, I get the following error when I run the command:

python automatedPreProcessing/automatedPreProcessing.py -m diameter -i test/Case_test_artery/artery.vtp -c 1.3

--- Working on case: artery 

--- Load model file

--- Get centerlines

--- No smoothing of surface

--- Computing distance to sphere
--- Computing mesh

Not capping surface
Remeshing surface
Iteration 1/10
Iteration 2/10
Iteration 3/10
Iteration 4/10
Iteration 5/10
Iteration 6/10
Iteration 7/10
Iteration 8/10
Iteration 9/10
Iteration 10/10
Final mesh improvement
Computing projection
Generating boundary layer
Capping inner surface
Remeshing endcaps
Iteration 1/10
Iteration 2/10
Iteration 3/10
Iteration 4/10
Iteration 5/10
Iteration 6/10
Iteration 7/10
Iteration 8/10
Iteration 9/10
Iteration 10/10
Final mesh improvement
Computing sizing function
Generating volume mesh
TetGen command line options: pq1.414000q10.000000q165.000000YsT1.000000e-08zQm
Internalerror in findedge():  Unable to find an edge in subface.
zsh: segmentation fault  python automatedPreProcessing/automatedPreProcessing.py -m diameter -i  -c 1.

**Comment by keiyamamo** [comment]
Hi,

I may not be the best one to answer here, but have you checked https://vampy.readthedocs.io/en/latest/installation.html#known-issues ?

**Comment by Owais-Khan** [comment]
Hi Kei,

I fixed the known issues that were on the website. However, it seems like it is more related to generating a volumetric mesh.

Regards,

Owais Khan

**Comment by keiyamamo** [comment]
Hi Owais,

I just donwload VamPy again and tried the same command as you but did not get the error. 
Are you running the command on the  `vmtk` conda environment ?

Best,
Kei

**Comment by hkjeldsberg** [comment]
Dear @Owais-Khan,

I have experienced similar errors myself, and partly concluded that this is an external issue with the mesh generator (TetGen). It could be an issue with the VMTK-wrapper, and maybe an upcoming version would fix that, but I am unsure.

A temporary fix that has worked for me is to **remove** the `.vtu` and `.xml.gz`, and rerun the meshing command, i.e.:
`python automatedPreProcessing/automatedPreProcessing.py -m diameter -i test/Case_test_artery/artery.vtp -c 1.3`

Best,
Henrik

**Comment by Owais-Khan** [comment]
Hi Henrik and Kei,

I re-installed vmtk and was able to successfully run the command, but got the following warning. Is this normal?

WARNING: POTENTIAL CONNECTIVITY ISSUE. 
         A distance between connected points is suspicious.
         The segment(s) of CELL ID VTK [0, 3]
         and, the segment(s) of CELL ID VTK [1] will be considered
         as connected. Please check if this action was expected.

WARNING: POTENTIAL CONNECTIVITY ISSUE. 
         A distance between connected points is suspicious.
         The segment(s) of CELL ID VTK [0, 3]
         and, the segment(s) of CELL ID VTK [4] will be considered
         as connected. Please check if this action was expected.

**Comment by Owais-Khan** [comment]
I have a second issue as well: When I changed the coarsening factor to 1.0 for the artery test case, the script crashes with the following error. It shouldn't happen if we are decreasing the coarsening factor. Can you please try it and let me know if it works for you?

TetGen command line options: pq1.414000q10.000000q165.000000YsT1.000000e-08zQm
Internalerror in findedge():  Unable to find an edge in subface.
ERROR: In ../vtkVmtk/Misc/vtkvmtkTetGenWrapper.cxx, line 431
vtkvmtkTetGenWrapper (0x7f944a736e80): TetGen quit with an exception.

**Comment by keiyamamo** [comment]
Hi Owasis,

As for the warning, please see here : https://github.com/KVSlab/VaMPy/issues/16#issuecomment-84387463

**Comment by Owais-Khan** [comment]
Hi,

I have created a repository that contains tools for compatibility with VaMPY and Oasis. Please visit my repo OasisTools. 

Since I was having trouble generating meshes with VMTK, probably because of Tetgen wrapper, I will rely on SimVascular for mesh generation. This is also useful for me when I want to run simulations of coronaries, which can’t be properly segmented with VMTK. I have written a script that can convert SimVascular meshes to .xml.gz meshes that can be read into Oasis. Please feel free to incorporate this into VaMpy if you wish. 

I have few other suggestions that I will provide as I move along the simulation pipeline.

Regards, 

Owais Khan
