### ISSUE TITLE
Discontinuity of plot made by `visualize_probes.py`

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaMPy#52]
Hi,

I  noticed that the lines are not continuous in the plot made by `visualize_probes.py`.
We can avoid this problem by only plotting after reading all the probes. 

![Screen Shot 2022-01-11 at 12 00 55](https://user-images.githubusercontent.com/42674006/148931669-24e41e58-b547-4fdc-b9fd-750d3ff3c042.png)

**Comment by hkjeldsberg** [comment]
Hi Kei,

Thanks for reporting this issue! There is a patch for this in PR #53, which should fix this.
