### ISSUE TITLE
Error when running Pre-processing

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/VaMPy#54]
HI @hkjeldsberg , 

I was trying to run the `automatedPreProcessing.py` for one of the case from aneurisk data set (one of ten healthy data set I got from you). 
However, I got the following error message.

```
--- Working on case: P0086 

--- Load model file

--- Get centerlines

--- No smoothing of surface

--- Computing distance to sphere

--- Computing flow rates and flow split, and setting boundary IDs

Traceback (most recent call last):
  File "automatedPreProcessing/automatedPreProcessing.py", line 505, in <module>
    run_pre_processing(**read_command_line())
  File "automatedPreProcessing/automatedPreProcessing.py", line 321, in run_pre_processing
    find_boundaries(path.join(dir_path, case_name), mean_inflow_rate, network, mesh, verbose_print, is_atrium)
  File "/Users/keiyamamoto/Documents/Aneurysm_workflow/automatedPreProcessing/common.py", line 608, in find_boundaries
    surfaceCellEntityIdsArray.DeepCopy(boundarySurface.GetCellData().GetArray('CellEntityIds'))
TypeError: ambiguous call, multiple overloaded methods match the arguments

```

Have you seen this error message before ? 
I used paraview to clip some part of the model and exported as `vtp` file before running `automatedPreProcessing.py`. 

Best,
Kei

**Comment by hkjeldsberg** [comment]
Hi @keiyamamo,

Cannot recall seeing this error before. Could you provide the command you used for running `automatedPreProcessing.py`? 
And are you running the latest version of Vampy? 


I tested this on the same model (also clipped prior to meshing), and I did not experience this issue. 
The command I used was: 
`python automatedPreProcessing/automatedPreProcessing.py -i models/P0086/model_cut.vtp -m diameter -c 1.3  -flo 1 -fli 1`

**Comment by keiyamamo** [comment]
Hi @hkjeldsberg  

Thank you for the message !
I just tested the same command you provided but it gave me the same error. 

```
(morphman) KeinoMacBook-Pro:Aneurysm_workflow keiyamamoto$ python automatedPreProcessing/automatedPreProcessing.py -m diameter -i /Users/keiyamamoto/Documents/models_aneurisk_healthy/P0086/surface/P0086.vtp -c 1.3 -fli 2 -flo 1

--- Working on case: P0086 

--- Load model file

--- Get centerlines

--- No smoothing of surface

--- Computing distance to sphere

--- Computing flow rates and flow split, and setting boundary IDs

Traceback (most recent call last):
  File "automatedPreProcessing/automatedPreProcessing.py", line 505, in <module>
    run_pre_processing(**read_command_line())
  File "automatedPreProcessing/automatedPreProcessing.py", line 321, in run_pre_processing
    find_boundaries(path.join(dir_path, case_name), mean_inflow_rate, network, mesh, verbose_print, is_atrium)
  File "/Users/keiyamamoto/Documents/Aneurysm_workflow/automatedPreProcessing/common.py", line 608, in find_boundaries
    surfaceCellEntityIdsArray.DeepCopy(boundarySurface.GetCellData().GetArray('CellEntityIds'))
TypeError: ambiguous call, multiple overloaded methods match the arguments
```

And yes, I’m using the latest version of Vampy. I just git pulled yesterday and switched to use `morphman` and this error happened. So, I’m guessing there is something wrong with my installation but I’m not really sure what is the problem as I followed the instructions (used `apply_vmtk_hotfix.py` as well...)

**Comment by hkjeldsberg** [comment]
Hi @keiyamamo,

Could you perhaps share the model you are working on? Then I can see if I experience the same issue, and maybe i can figure out the issue.

**Comment by keiyamamo** [comment]
Thank you for the suggestion ! I’ll send it to you by email.

Best,
Kei
